name: CI
on:
  push:
    branches: [master, next]
  pull_request:
    branches: [master, next]
permissions:
  contents: read
  id-token: write
jobs:
  test-node:
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1
      - name: prepare node
        uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: install playwright
        run: npx playwright install --with-deps
      - name: install npm
        run: npm cit
      - name: upload test report
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: ${{ github.workspace }}/playwright-report/**/*
          retention-days: 30
        if: ${{ !cancelled() }}
